### ISSUE TITLE
Add shortcode for Google Docs

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake-bakery#113]
It should also reverse this:

```
<iframe width="400" height ="800" src="https://docs.google.com/spreadsheets/d/1mtvInQiuHtJMjcbu38pZp96fv5M6jpe9CjlR4yjfqpE/pubhtml?widget=true&amp;headers=false"></iframe>
```

**Comment by goldenapples** [comment]
While we're adding it, we might as well match all the types of Google Docs available for embed:

- [ ] **Docs** `<iframe src="https://docs.google.com/document/d/1TwnxIligMjh1FLa1AWCB7F4xstvLrYrhJFqPqObvmK8/pub?embedded=true"></iframe>`

- [ ] **Sheets** `<iframe width="400" height ="800" src="https://docs.google.com/spreadsheets/d/1mtvInQiuHtJMjcbu38pZp96fv5M6jpe9CjlR4yjfqpE/pubhtml?widget=true&amp;headers=false"></iframe>`

- [ ] **Slides** `<iframe src="https://docs.google.com/presentation/d/1tQ4Q1wFpKNLj9BW8s_pCYgDMFXIeHskvTQWaRBS-aGc/embed?start=false&loop=false&delayms=3000" frameborder="0" width="960" height="569" allowfullscreen="true" mozallowfullscreen="true" webkitallowfullscreen="true"></iframe>`

- [ ] **Forms** `<iframe src="https://docs.google.com/forms/d/1DwyXsL7kmR2F8-0q0XAecLTwO5_xPeN1tN-ex2Zs_hY/viewform?embedded=true" width="760" height="500" frameborder="0" marginheight="0" marginwidth="0">Loading...</iframe>`

- [ ] **Maps** `<iframe src="https://www.google.com/maps/d/u/1/embed?mid=zEkbFn1A1xVE.kLg_5uTIa64Q" width="640" height="480"></iframe>`

- [ ] **Drawings** `<img src="https://docs.google.com/drawings/d/1WRklYKAG0B3uJrvcd5WNaaG-UABEZnfKFOes0L-kaK8/pub?w=960&amp;h=720">`

**Comment by goldenapples** [comment]
This is :ship:
