### ISSUE TITLE
facebook shortcode not rendering html

### ISSUE THREAD

**Issue by montchr** [wp-shortcake/shortcake-bakery#146]
I've tried with three public posts from different pages and none of the URLs work in the shortcode. Using fresh install of WP 4.3.1 with fresh clones of Shortcake and Shortcake Bakery.

```
[facebook url="https://www.facebook.com/boingboing/posts/10153226877361179"]

[facebook url="https://www.facebook.com/residentadvisor/posts/10153393199684480"]
```

---

![](http://cl.montchr.io/image/1j2Y0W1h0m2M/download/Image%202015-11-12%20at%2010%3A08%3A45.png)

---

![](http://cl.montchr.io/image/162j0L0Q0S3N/Image%202015-11-12%20at%2010%3A09%3A25.png)

**Comment by danielbachhuber** [comment]
Works for me in the admin on trunk and WP 4.3.1:

![image](https://cloud.githubusercontent.com/assets/36432/11125376/767a8d20-891e-11e5-8dd3-fac8632188cc.png)

However, it doesn't render on the frontend:

![image](https://cloud.githubusercontent.com/assets/36432/11125427/baa6450c-891e-11e5-8f52-a2b6180b0d79.png)

**Comment by montchr** [comment]
Checked it out on master. It works! Thanks so much.
