### ISSUE TITLE
giphy shortcode crops gif

### ISSUE THREAD

**Issue by montchr** [wp-shortcake/shortcake-bakery#149]
Here's the GIF on my site:

![](http://cl.montchr.io/image/0d3R1i120O3b/Image%202015-11-17%20at%2008%3A24%3A51.png)

Note that bottom text is cut off.

Here's the full-sized GIF on Giphy:

![](http://i.giphy.com/FcHcQIpQD5Bmg.gif)

Seems that in making the small-sized GIF full-width, it crops the image.

**Comment by danielbachhuber** [comment]
Can you share the full shortcode you're using?

**Comment by montchr** [comment]
`[giphy url="http://giphy.com/gifs/mulder-wheelies-FcHcQIpQD5Bmg"]`
