### ISSUE TITLE
Infogram shortcode no longer working since domain change

### ISSUE THREAD

**Issue by montchr** [wp-shortcake/shortcake-bakery#212]
Infogram recently changed its domain from `infogr.am` to `infogram.com`. Shortcake Bakery does not account for this in `Infogram::callback()` when [removing the domain from the URL to get the ID](https://github.com/wp-shortcake/shortcake-bakery/blob/master/inc/shortcodes/class-infogram.php#L75), meaning that nothing will render.

**Comment by goldenapples** [comment]
Fixed in #217.
