### ISSUE TITLE
"Add Embed" experience for shortcode reversal

### ISSUE THREAD

**Issue by danielbachhuber** [wp-shortcake/shortcake-bakery#85]
VIP has this existing UX for adding protected embeds:

![image](https://cloud.githubusercontent.com/assets/36432/10008496/045bea58-6084-11e5-8be5-f2c23867cc7e.png)

![image](https://cloud.githubusercontent.com/assets/36432/10008505/1c00d100-6084-11e5-8fdb-6b8771c2d855.png)

We should create something similar for Shortcake Bakery, but instead perform a shortcode reversal and insert the found shortcode.

**Comment by danielbachhuber** [comment]
Bumping this to `priority:high` because we should really land this Monday if we can, to get it in-front of users.

**Comment by goldenapples** [comment]
:ship:
